#!/bin/bash
#
#1.2..bim..4..bum

for i in $(seq 1 100)
do 
	if [ $(expr $i % 15) -eq 0 ]
	then
		echo "bimbum"
	elif [ $(expr $i % 3) -eq 0 ]
	then
		echo "bim"
	elif [ $(expr $i % 5) -eq 0 ]
	then 
		echo "bum"
	else
		echo $i
	fi
done
	
