#!/bin/bash
#
# olvass be egy az első paraméterben megadott file-t, és add össze a benne lévő számokat 
# a számokat szóközök vagy enterek választják el egymástól

# minta.be
# 1
# 2 3
# 2
# 6 7 1

osszeg=0

while read sor || [[ -n $sor ]]
do
	#IFS=","
	for szam in $sor
	do
		(( osszeg+=szam ))
	done
done < $1

echo $osszeg
